<?php

return [
    'site_name' => env('SEO_SITE_NAME', 'Bwiser'),
    'site_url' => env('SEO_SITE_URL', env('APP_URL', 'https://bwiser.co.za')),
    'default_locale' => env('SEO_DEFAULT_LOCALE', 'en_ZA'),
    'theme_color' => env('SEO_THEME_COLOR', '#2563eb'),
    'twitter_site' => env('SEO_TWITTER_SITE', '@bwiser'),
    'facebook_app_id' => env('SEO_FACEBOOK_APP_ID', ''),
    'support_email' => env('SEO_SUPPORT_EMAIL', 'support@bwiser.co.za'),
    'contact_phone' => env('SEO_CONTACT_PHONE', ''),
    'same_as' => array_values(array_filter(array_map('trim', explode(',', (string) env('SEO_SAME_AS', ''))))),

    'sitemap' => [
        'excluded_route_names' => [
            'logout',
            'auth.google.redirect',
            'auth.google.callback',
            'auth.google.complete.form',
            'auth.google.complete.store',
            'registration.complete',
            'registration.documents.store',
            'here.geocode',
            'here.reverse',
            'sitemap',
            'driver.repayments.request.show',
            'driver.repayments.request.pay',
            'driver.repayments.request.callback',
        ],
        'excluded_name_prefixes' => [
            'admin.',
            'driver.',
            'merchant.',
            'employee.',
            'investor.',
        ],
        'excluded_uri_prefixes' => [
            'api',
            'admin',
            'driver',
            'merchant',
            'employee',
            'investor',
            'payments',
            'repayments/request',
            'broadcasting',
            'sanctum',
            'up',
            'clear-cache',
            'setup-roles',
            'test-roles',
            'add-investor-role',
        ],
    ],
];
